apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      shareProcessNamespace: true
      containers:
        - name: cricket
          image: jamesmilligan/cricket
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
        - name: sidecar
          image: jamesmilligan/sidecar
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"



          